### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by csufangyu** [BertaBescos/DynaSLAM#1]
thanks for your work! I try to run ,but I meet a problems,could you help me???
when I run your code! I meet a error which is ：
Segment error (core dumped)
then I find the error occur at the function this->py_module = PyImport_ImportModule(this->module_name.c_str());this->class_name.c_str()) in the file of MaskNet.cc !and it return the null, I can not solve it ! can you help me?thanks!

**Comment by csufangyu** [comment]
I think the reason maybe the version of python! could you help me??

**Comment by BertaBescos** [comment]
Hi, it is possible that you do not have installed some of the Mask R-CNN required packages. Run the provided python script `src/python/Check.py` to check if everything needed for Mask R-CNN is properly installed.

**Comment by csufangyu** [comment]
Thanks for your answer, and I try to do it.I run the Check.py  and no error. but when I run the code ,the error also happened.And I debug it ,and I meet the error is:
ImportError: numpy.core.multiarray failed to import
And if I run the MaskRCNN.py, it is no such error!could you tell me the version of numpy??I guess it maybe influenced by the version of numpy! thanks very much!

**Comment by BertaBescos** [comment]
I am using Python 2.7 and numpy 1.15.2.

**Comment by csufangyu** [comment]
thanks very much.But I find the some code is python3，and It does not matter?-------- 原始邮件 --------主题：Re: [BertaBescos/DynaSLAM] make error (#1)发件人：BertaBescos 收件人：BertaBescos/DynaSLAM 抄送：universe ,Author I am using Python 2.7 and numpy 1.15.2.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BertaBescos/DynaSLAM","title":"BertaBescos/DynaSLAM","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/BertaBescos/DynaSLAM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BertaBescos in #1: I am using Python 2.7 and numpy 1.15.2."}],"action":{"name":"View Issue","url":"https://github.com/BertaBescos/DynaSLAM/issues/1#issuecomment-433879822"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BertaBescos/DynaSLAM/issues/1#issuecomment-433879822",
"url": "https://github.com/BertaBescos/DynaSLAM/issues/1#issuecomment-433879822",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [BertaBescos/DynaSLAM] make error (#1)",
"sections": [
{
"text": "",
"activityTitle": "**BertaBescos**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@BertaBescos",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"BertaBescos/DynaSLAM\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"BertaBescos/DynaSLAM\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/BertaBescos/DynaSLAM/issues/1#issuecomment-433879822"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401940849\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by BertaBescos** [comment]
Did you get it to work?

**Comment by csufangyu** [comment]
No,I am trying to run，but IT failed!and the nvidia get some error.now I am try to install nvidia!thanks very much.I find some codes are python2，others are python3.-------- 原始邮件 --------主题：Re: [BertaBescos/DynaSLAM] make error (#1)发件人：BertaBescos 收件人：BertaBescos/DynaSLAM 抄送：universe ,Author Did you get it to work?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BertaBescos/DynaSLAM","title":"BertaBescos/DynaSLAM","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/BertaBescos/DynaSLAM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BertaBescos in #1: Did you get it to work?"}],"action":{"name":"View Issue","url":"https://github.com/BertaBescos/DynaSLAM/issues/1#issuecomment-434287454"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BertaBescos/DynaSLAM/issues/1#issuecomment-434287454",
"url": "https://github.com/BertaBescos/DynaSLAM/issues/1#issuecomment-434287454",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [BertaBescos/DynaSLAM] make error (#1)",
"sections": [
{
"text": "",
"activityTitle": "**BertaBescos**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@BertaBescos",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"BertaBescos/DynaSLAM\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"BertaBescos/DynaSLAM\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/BertaBescos/DynaSLAM/issues/1#issuecomment-434287454"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401940849\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by BertaBescos** [comment]
I have removed those files that are python3, since they are unused. Thanks for pointing that out.

**Comment by csufangyu** [comment]
thanks!
