### ISSUE TITLE
About the speed of segmenting image using Mask-rcnn

### ISSUE THREAD

**Issue by jsdd25** [BertaBescos/DynaSLAM#17]
Hello! This work is amazing! I want to measure the speed of image semantic segmentation. I use the chrono to measure the speed in the rgbd_tum.cc as follows:
```
std::chrono::steady_clock::time_point t3 = std::chrono::steady_clock::now();
maskRCNN=MaskNet->GetSegmentation(imRGB,string(argv[5]),vstrImageFilenamesRGB[ni].replace(0,4,""));
std::chrono::steady_clock::time_point t4 = std::chrono::steady_clock::now();
double seg_time= std::chrono::duration_cast<std::chrono::duration<double> >(t4 - t3).count();
```
It seems that the time of segmentation is about 1ms for each frame. However, I also measure the time of segmentation in the MaskRCNN.py as follows:
```
tic = time.time()
results = self.model.detect([image], verbose=0)
seg_time = time.time() - tic
print (seg_time)
```
However, the seg_time only shows once and is 1.23s. Is the `GetDynSeg(self, image, image2=None)` function in this python file only called once? How long does it take to  segment an image? Thank you very much!

**Comment by BertaBescos** [comment]
Hi @jsdd25! Thanks for the nice words!
I have never measured its speed but your code seems to be alright. I am thinking that maybe you have the masks already stored from a previous run? And that is why GetDynSeg is only called once (in the initialization). Check the ```src/MaskNet.cc``` file:

```cv::Mat SegmentDynObject::GetSegmentation(cv::Mat &image,std::string dir, std::string name){
    cv::Mat seg = cv::imread(dir+"/"+name,CV_LOAD_IMAGE_UNCHANGED);
    if(seg.empty()){
        PyObject* py_image = cvt->toNDArray(image.clone());
        assert(py_image != NULL);
        PyObject* py_mask_image = PyObject_CallMethod(this->net, const_cast<char*>(this->get_dyn_seg.c_str()),"(O)",py_image);
        [...]
    }
    return seg;
}
