### ISSUE TITLE
hard initialize and easy lose in mono style

### ISSUE THREAD

**Issue by Chrislzy1993** [BertaBescos/DynaSLAM#20]
in mono style, i find there are two difficulty
1. it is too hard to initialize
![1553070108459](https://user-images.githubusercontent.com/17810965/54669663-ebe7ec00-4b2c-11e9-8bf1-666dbf3a217e.png)
2. it is too easy to lose localization
![1553069903623](https://user-images.githubusercontent.com/17810965/54669738-1639a980-4b2d-11e9-9158-f88b2dea2389.png)

in question #12 , advise to uprise the detect num,  i try it , but has nothing different. its anything i can done to solve this problem, like imu ????

**Comment by Chrislzy1993** [comment]
@jmfacil @BertaBescos , thanks a lot

**Comment by jmfacil** [comment]
Initialization when using monocular is usually more difficult of course. It depends on the sequence (i.e. the parallax, the features, dynamic objects....) including more sensors like infrared cameras (RGB-D), Stereo and/or IMU would help if fuse correctly for sure. But we are not planning to include IMU integration.

**Comment by Chrislzy1993** [comment]
enen, thanks a lot , when i test tum other dateset , like rgbd_dataset_freiburg3_walking_rpy,  it can work well, may be the problem is in dataset.
