### ISSUE TITLE
Light Tracking not working because Tracking is not initialized...

### ISSUE THREAD

**Issue by jianbozhanghit** [BertaBescos/DynaSLAM#4]
There is a problem for me. When I run the command" ./Examples/RGB-D/rgbd_tum Vocabulary/ORBvoc.txt Examples/RGB-D/TUM1.yaml ........", there will always be  a problem:"Light Tracking not working because Tracking is not initialized...". Could you tell me the reason for that? Thank you very much.

**Comment by BertaBescos** [comment]
Hi! Do you have the last version of the github repo?  I fixed this issue a few weeks ago.
