### ISSUE TITLE
segment picture size

### ISSUE THREAD

**Issue by qxdaaaaa** [BertaBescos/DynaSLAM#40]
cv::Mat image  = cv::Mat::zeros(480,640,CV_8UC3); //Be careful with size!!
@BertaBescos @jmfacil  Can i change the pucture size ,such as 960*540and it will case the lower
 velocity of segment??

**Comment by haliphinx** [comment]
@qxdaaaaa As far as I see, yes you can, I made change for the image size and it works in the mono case. Make sure you also change the size in mono_tum.cc as well.
```
// Segment out the images
        cv::Mat mask = cv::Mat::ones(480,640,CV_8U);
```
For other cases like RGB-D, I guess they are more or less the same.
