### ISSUE TITLE
the git instruction has no authority

### ISSUE THREAD

**Issue by Hewenly** [BertaBescos/DynaSLAM#5]
git clone git@github.com:BertaBescos/DynaSLAM.git
Cloning into 'DynaSLAM'...
The authenticity of host 'github.com (xxx.xxx.xxx.xxx)' can't be established.
RSA key fingerprint is *******.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '**********' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(while I can use git clone --recursive to clone)

**Comment by BertaBescos** [comment]
Thanks! I changed the instruction to ``git clone https://github.com/BertaBescos/DynaSLAM.git``.
