### ISSUE TITLE
Segmentation fault when run PyArray_Check(o) in NDArrayConverter::toMat in src/Conversion.cc

### ISSUE THREAD

**Issue by linpeisensh** [BertaBescos/DynaSLAM#65]
The result is shown in the following image:
![image](https://user-images.githubusercontent.com/52672986/104753048-c2fc0680-5757-11eb-836a-25a7853b5422.png)
The MaskRCNN is initialized successfully, but Segmentation fault occurs, when run PyArray_Check(o) in NDArrayConverter::toMat in src/Conversion.cc.
I have checked NDArrayConverter::init() run before this PyArray_Check(o), that means I have "Py_Initialize();" and " _import_array();".
![image](https://user-images.githubusercontent.com/52672986/104753240-fe96d080-5757-11eb-971c-812e10909030.png)

Could someone tell me how to solve this problem?

**Comment by Skywalker666666** [comment]
Excuse me, How you solved this problem?

**Comment by Skywalker666666** [comment]
@linpeisensh  how do you figure out this one?

**Comment by linpeisensh** [comment]
Sorry, I have no idea how to solve it.
