### ISSUE TITLE
some wrong about the ndarrayobject.h

### ISSUE THREAD

**Issue by dongdingcheng** [BertaBescos/DynaSLAM#7]
![00](https://user-images.githubusercontent.com/35513340/49853426-13d6fd80-fe22-11e8-8ece-bffb8b9b4bd0.png)
When I build the project, I meet the error that I couldn't find ndarrayobject.h, I don't know what is it, and how can I solve the problem?

**Comment by HaiDang2001VN** [comment]
@dongdingcheng , thanks for asking this question.
Now I'm facing the same issue here, could you please provide me any information or note about solving this problem. Glad to hear your way!

**Comment by dongdingcheng** [comment]
@HaiDang2001VN , this problem occured because you haven't set the pythonpath accurately.
You should check your CMakeList.txt
