### ISSUE TITLE
something wrong about the output of the depth 

### ISSUE THREAD

**Issue by dongdingcheng** [BertaBescos/DynaSLAM#9]
Hi，I'm afraid I need to disturb you again. When I test the rgbd-slam， I found that the folder of the depth output image is empty. Maybe there is some wrong in the code。

**Comment by dongdingcheng** [comment]
OK, I have solved the problem, it need add vstrImageFilenamesD[ni].replace(0,6,""); before the cv::imwrite(string(argv[6]) + "/depth/" + vstrImageFilenamesD[ni],imDOut); in rgbd_tum.cc in line 154

**Comment by BertaBescos** [comment]
Thanks a lot! I did not have time to check it out yesterday. Do you mind writing a pull request with your solution?

**Comment by BertaBescos** [comment]
I updated the rgbd_tum example. Thanks a lot! I close the issue.
