### ISSUE TITLE
Arxiv review version said The project code will be released upon acceptance. [The RAL published version deleted this sentence]

### ISSUE THREAD

**Issue by Kin-Zhang** [BertaBescos/DynaSLAM#93]
Here are two screenshots of the paper on review and publication. You deleted quite an important sentence (which promised public code on review) on the RAL version...

![image](https://user-images.githubusercontent.com/35365764/206842347-9b955471-d145-4b52-95cb-520973507709.png)

![image](https://user-images.githubusercontent.com/35365764/206842352-428ca482-fe7e-416b-8136-938b47a384a0.png)

I think if the next time you don't want to open-source, there is no need to write this sentence in the version under review.

**Comment by Kin-Zhang** [comment]
Related issues: https://github.com/BertaBescos/DynaSLAM/issues/91, https://github.com/BertaBescos/DynaSLAM/issues/92

**Comment by Hello-Water** [comment]
@Kin-Zhang 
It mentioned in RAL that DynaSLAM Ⅱ is an open-source SLAM system.
![Screenshot 2023-01-05 09:04:55](https://user-images.githubusercontent.com/30867133/210678800-f36f5244-a4ef-456e-b747-a2bacd8ad957.png)
